on: 
  pull_request:
  workflow_dispatch:

# Please, note that this cancels any workflows that may be currently in progress,
# when a new one gets started.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  test-examples:
    runs-on: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v3
    
      - name: get latest roc nightly
        run: |
          curl -fOL https://github.com/roc-lang/roc/releases/download/nightly/roc_nightly-linux_x86_64-latest.tar.gz

      - name: rename nightly tar
        run: mv $(ls | grep "roc_nightly.*tar\.gz") roc_nightly.tar.gz

      - name: decompress the tar
        run: tar -xzf roc_nightly.tar.gz

      - run: rm roc_nightly.tar.gz

      - name: simplify nightly folder name
        run: mv roc_nightly* roc_nightly

      # Check Roc version
      - run: ./roc_nightly/roc version

      # Run all tests 
      - run: ROC=./roc_nightly/roc ./ci/run-tests.sh

